# Generated by Django 4.2 on 2023-05-01 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', models.CharField(blank=True, choices=[('MoCo', 'Mobiles & Computers'), ('TVAE', 'TV, Appliances & Electronics'), ('MFas', "Men's Fashion"), ('WFas', "Women's Fashion"), ('Book', 'Books'), ('Kitc', 'Kitchen')], max_length=4)),
                ('name', models.CharField(max_length=255)),
                ('short', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('featured', models.BooleanField()),
                ('instock', models.IntegerField()),
                ('product_img', models.ImageField(default='default.jpg', upload_to='image/')),
                ('category', models.ManyToManyField(blank=True, to='products.categories')),
            ],
        ),
    ]
