# Generated by Django 4.2 on 2023-05-01 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', models.CharField(blank=True, choices=[('MoCo', 'Mobiles & Computers'), ('TVAE', 'TV, Appliances & Electronics'), ('RE', 'Real Estate'), ('AP', 'Art Pieces'), ('Book', 'Books'), ('Jewel', 'Jewellery')], max_length=5)),
                ('name', models.CharField(max_length=255)),
                ('short', models.CharField(max_length=4)),
            ],
        ),
        migrations.DeleteModel(
            name='Categories',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(blank=True, to='products.category'),
        ),
    ]
